<?php

use Illuminate\Database\Seeder;

class FoodTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('food')->delete();
        
        DB::table('food')->insert(array (
            0 => 
            array (
                
                'rsId' => 1,
                'fdName' => '韭菜',
                'cId' => 1,
                'gram' => 71.0,
                'calorie' => 18.0,
                'protein' => 1.5,
                'fat' => 0.3,
                'saturatedFat' => 0.1,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 3.0,
                'sugar' => 0.8,
                'dietaryFiber' => 1.7,
                'sodium' => 101.0,
                'calcium' => 39.0,
                'potassium' => 226.0,
                'ferrum' => 1.0,
                'photo' => 'http://120.110.112.96/qrfood/img/01.jpg',
                'disable' => 0,
                'created_at' => '2019-11-27 19:49:36',
                'updated_at' => '2019-12-01 17:53:38',
            ),
            1 => 
            array (
                
                'rsId' => 1,
                'fdName' => '白菜滷',
                'cId' => 1,
                'gram' => 111.0,
                'calorie' => 72.9,
                'protein' => 1.4,
                'fat' => 5.3,
                'saturatedFat' => 0.9,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 5.3,
                'sugar' => 2.4,
                'dietaryFiber' => 1.1,
                'sodium' => 865.1,
                'calcium' => 44.8,
                'potassium' => 189.0,
                'ferrum' => 0.6,
                'photo' => 'http://120.110.112.96/qrfood/img/02.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:33:58',
            ),
            2 => 
            array (
                
                'rsId' => 1,
                'fdName' => '花椰菜',
                'cId' => 1,
                'gram' => 35.0,
                'calorie' => 52.0,
                'protein' => 0.5,
                'fat' => 5.0,
                'saturatedFat' => 0.8,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 1.7,
                'sugar' => 0.9,
                'dietaryFiber' => 0.7,
                'sodium' => 694.0,
                'calcium' => 9.0,
                'potassium' => 87.0,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/03.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:01',
            ),
            3 => 
            array (
                
                'rsId' => 1,
                'fdName' => '金針菇',
                'cId' => 1,
                'gram' => 90.0,
                'calorie' => 80.0,
                'protein' => 2.3,
                'fat' => 5.4,
                'saturatedFat' => 0.9,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 7.0,
                'sugar' => 2.5,
                'dietaryFiber' => 2.3,
                'sodium' => 691.0,
                'calcium' => 7.0,
                'potassium' => 345.0,
                'ferrum' => 1.0,
                'photo' => 'http://120.110.112.96/qrfood/img/04.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:05',
            ),
            4 => 
            array (
                
                'rsId' => 1,
                'fdName' => '絲瓜',
                'cId' => 1,
                'gram' => 74.0,
                'calorie' => 57.0,
                'protein' => 0.7,
                'fat' => 5.1,
                'saturatedFat' => 0.9,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 3.0,
                'sugar' => 1.6,
                'dietaryFiber' => 0.7,
                'sodium' => 691.0,
                'calcium' => 9.0,
                'potassium' => 93.0,
                'ferrum' => 0.2,
                'photo' => 'http://120.110.112.96/qrfood/img/05.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:07',
            ),
            5 => 
            array (
                
                'rsId' => 1,
                'fdName' => '高麗菜',
                'cId' => 1,
                'gram' => 80.0,
                'calorie' => 19.0,
                'protein' => 1.0,
                'fat' => 0.1,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 3.8,
                'sugar' => 0.0,
                'dietaryFiber' => 1.0,
                'sodium' => 9.7,
                'calcium' => 36.5,
                'potassium' => 143.4,
                'ferrum' => 0.4,
                'photo' => 'http://120.110.112.96/qrfood/img/06.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:10',
            ),
            6 => 
            array (
                
                'rsId' => 1,
                'fdName' => '薑絲苦瓜',
                'cId' => 1,
                'gram' => 73.0,
                'calorie' => 107.0,
                'protein' => 1.0,
                'fat' => 5.3,
                'saturatedFat' => 0.9,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 34.2,
                'sugar' => 0.3,
                'dietaryFiber' => 2.3,
                'sodium' => 812.0,
                'calcium' => 18.0,
                'potassium' => 156.0,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/07.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:12',
            ),
            7 => 
            array (
                
                'rsId' => 1,
                'fdName' => '空心菜',
                'cId' => 1,
                'gram' => 55.0,
                'calorie' => 57.0,
                'protein' => 1.1,
                'fat' => 5.2,
                'saturatedFat' => 0.9,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 2.3,
                'sugar' => 0.0,
                'dietaryFiber' => 1.4,
                'sodium' => 723.0,
                'calcium' => 38.0,
                'potassium' => 214.0,
                'ferrum' => 1.2,
                'photo' => 'http://120.110.112.96/qrfood/img/08.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:15',
            ),
            8 => 
            array (
                
                'rsId' => 1,
                'fdName' => '油菜',
                'cId' => 1,
                'gram' => 73.0,
                'calorie' => 10.0,
                'protein' => 1.2,
                'fat' => 0.1,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 1.3,
                'sugar' => 0.0,
                'dietaryFiber' => 0.9,
                'sodium' => 68.8,
                'calcium' => 72.9,
                'potassium' => 211.5,
                'ferrum' => 1.8,
                'photo' => 'http://120.110.112.96/qrfood/img/09.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:17',
            ),
            9 => 
            array (
                
                'rsId' => 1,
                'fdName' => '番茄炒蛋',
                'cId' => 4,
                'gram' => 102.0,
                'calorie' => 99.36,
                'protein' => 8.64,
                'fat' => 6.0,
                'saturatedFat' => 2.04,
                'transFat' => 0.0,
                'cholesterol' => 255.0,
                'carbohydrate' => 2.76,
                'sugar' => 0.84,
                'dietaryFiber' => 0.24,
                'sodium' => 93.36,
                'calcium' => 30.96,
                'potassium' => 167.52,
                'ferrum' => 1.56,
                'photo' => 'http://120.110.112.96/qrfood/img/10.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:19',
            ),
            10 => 
            array (
                
                'rsId' => 1,
                'fdName' => '米血',
                'cId' => 3,
                'gram' => 66.0,
                'calorie' => 146.0,
                'protein' => 5.3,
                'fat' => 3.5,
                'saturatedFat' => 0.7,
                'transFat' => 30.4,
                'cholesterol' => 2.0,
                'carbohydrate' => 23.1,
                'sugar' => 0.1,
                'dietaryFiber' => 0.7,
                'sodium' => 937.0,
                'calcium' => 8.0,
                'potassium' => 66.0,
                'ferrum' => 7.8,
                'photo' => 'http://120.110.112.96/qrfood/img/11.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:22',
            ),
            11 => 
            array (
                
                'rsId' => 1,
                'fdName' => '辣炒筍子',
                'cId' => 1,
                'gram' => 65.0,
                'calorie' => 60.0,
                'protein' => 1.8,
                'fat' => 5.2,
                'saturatedFat' => 0.8,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 2.2,
                'sugar' => 0.1,
                'dietaryFiber' => 1.4,
                'sodium' => 740.0,
                'calcium' => 4.0,
                'potassium' => 49.0,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/12.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:24',
            ),
            12 => 
            array (
                
                'rsId' => 1,
                'fdName' => '皮蛋豆腐',
                'cId' => 2,
                'gram' => 84.0,
                'calorie' => 86.0,
                'protein' => 8.9,
                'fat' => 3.5,
                'saturatedFat' => 1.2,
                'transFat' => 0.0,
                'cholesterol' => 57.0,
                'carbohydrate' => 4.9,
                'sugar' => 0.0,
                'dietaryFiber' => 0.4,
                'sodium' => 161.0,
                'calcium' => 101.0,
                'potassium' => 165.0,
                'ferrum' => 1.9,
                'photo' => 'http://120.110.112.96/qrfood/img/13.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:27',
            ),
            13 => 
            array (
                
                'rsId' => 1,
                'fdName' => '彩椒杏鮑菇',
                'cId' => 1,
                'gram' => 47.0,
                'calorie' => 60.0,
                'protein' => 0.9,
                'fat' => 5.0,
                'saturatedFat' => 0.8,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 3.3,
                'sugar' => 0.9,
                'dietaryFiber' => 1.1,
                'sodium' => 690.0,
                'calcium' => 3.0,
                'potassium' => 109.0,
                'ferrum' => 0.2,
                'photo' => 'http://120.110.112.96/qrfood/img/14.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:29',
            ),
            14 => 
            array (
                
                'rsId' => 1,
                'fdName' => '醬炒茄子',
                'cId' => 1,
                'gram' => 86.0,
                'calorie' => 65.0,
                'protein' => 1.0,
                'fat' => 5.1,
                'saturatedFat' => 0.9,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 4.3,
                'sugar' => 1.9,
                'dietaryFiber' => 2.0,
                'sodium' => 691.0,
                'calcium' => 14.0,
                'potassium' => 196.0,
                'ferrum' => 0.4,
                'photo' => 'http://120.110.112.96/qrfood/img/15.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:31',
            ),
            15 => 
            array (
                
                'rsId' => 1,
                'fdName' => '黑胡椒豆干',
                'cId' => 2,
                'gram' => 69.0,
                'calorie' => 157.9,
                'protein' => 10.8,
                'fat' => 10.3,
                'saturatedFat' => 1.7,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 5.5,
                'sugar' => 0.0,
                'dietaryFiber' => 2.5,
                'sodium' => 909.1,
                'calcium' => 420.8,
                'potassium' => 143.0,
                'ferrum' => 3.0,
                'photo' => 'http://120.110.112.96/qrfood/img/16.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:34',
            ),
            16 => 
            array (
                
                'rsId' => 1,
                'fdName' => '醬燒豆腐',
                'cId' => 2,
                'gram' => 99.0,
                'calorie' => 145.0,
                'protein' => 8.6,
                'fat' => 8.7,
                'saturatedFat' => 1.7,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 8.3,
                'sugar' => 0.0,
                'dietaryFiber' => 0.9,
                'sodium' => 1195.0,
                'calcium' => 123.0,
                'potassium' => 226.0,
                'ferrum' => 2.1,
                'photo' => 'http://120.110.112.96/qrfood/img/17.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:37',
            ),
            17 => 
            array (
                
                'rsId' => 1,
                'fdName' => '炸豆輪',
                'cId' => 2,
                'gram' => 63.0,
                'calorie' => 173.0,
                'protein' => 12.6,
                'fat' => 11.1,
                'saturatedFat' => 1.8,
                'transFat' => 101.4,
                'cholesterol' => 0.0,
                'carbohydrate' => 6.2,
                'sugar' => 0.0,
                'dietaryFiber' => 0.4,
                'sodium' => 128.0,
                'calcium' => 4.0,
                'potassium' => 29.0,
                'ferrum' => 1.2,
                'photo' => 'http://120.110.112.96/qrfood/img/18.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:39',
            ),
            18 => 
            array (
                
                'rsId' => 1,
                'fdName' => '豆干海帶絲',
                'cId' => 4,
                'gram' => 97.0,
                'calorie' => 135.0,
                'protein' => 8.9,
                'fat' => 9.0,
                'saturatedFat' => 1.5,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 0.0,
                'sugar' => 0.0,
                'dietaryFiber' => 2.6,
                'sodium' => 1018.0,
                'calcium' => 162.0,
                'potassium' => 32.0,
                'ferrum' => 3.4,
                'photo' => 'http://120.110.112.96/qrfood/img/19.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:41',
            ),
            19 => 
            array (
                
                'rsId' => 1,
                'fdName' => '蒸蛋',
                'cId' => 2,
                'gram' => 76.0,
                'calorie' => 117.0,
                'protein' => 6.7,
                'fat' => 9.8,
                'saturatedFat' => 2.4,
                'transFat' => 50.7,
                'cholesterol' => 210.0,
                'carbohydrate' => 0.8,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 759.0,
                'calcium' => 27.0,
                'potassium' => 74.0,
                'ferrum' => 1.2,
                'photo' => 'http://120.110.112.96/qrfood/img/20.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:43',
            ),
            20 => 
            array (
                
                'rsId' => 1,
                'fdName' => '甜不辣',
                'cId' => 3,
                'gram' => 39.0,
                'calorie' => 77.0,
                'protein' => 4.8,
                'fat' => 1.8,
                'saturatedFat' => 0.4,
                'transFat' => 0.0,
                'cholesterol' => 8.0,
                'carbohydrate' => 10.3,
                'sugar' => 0.0,
                'dietaryFiber' => 0.1,
                'sodium' => 267.0,
                'calcium' => 8.0,
                'potassium' => 39.0,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/21.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:45',
            ),
            21 => 
            array (
                
                'rsId' => 1,
                'fdName' => '關東煮',
                'cId' => 4,
                'gram' => 82.0,
                'calorie' => 94.0,
                'protein' => 6.4,
                'fat' => 2.3,
                'saturatedFat' => 0.5,
                'transFat' => 0.0,
                'cholesterol' => 10.0,
                'carbohydrate' => 11.8,
                'sugar' => 0.7,
                'dietaryFiber' => 0.4,
                'sodium' => 1045.0,
                'calcium' => 19.0,
                'potassium' => 94.0,
                'ferrum' => 0.4,
                'photo' => 'http://120.110.112.96/qrfood/img/22.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:48',
            ),
            22 => 
            array (
                
                'rsId' => 1,
                'fdName' => '荷包蛋',
                'cId' => 2,
                'gram' => 50.0,
                'calorie' => 113.0,
                'protein' => 6.5,
                'fat' => 9.4,
                'saturatedFat' => 2.3,
                'transFat' => 50.7,
                'cholesterol' => 193.0,
                'carbohydrate' => 1.2,
                'sugar' => 0.1,
                'dietaryFiber' => 0.0,
                'sodium' => 170.0,
                'calcium' => 22.0,
                'potassium' => 76.0,
                'ferrum' => 0.9,
                'photo' => 'http://120.110.112.96/qrfood/img/23.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:50',
            ),
            23 => 
            array (
                
                'rsId' => 1,
                'fdName' => '四季豆炒香菇',
                'cId' => 4,
                'gram' => 59.0,
                'calorie' => 94.0,
                'protein' => 3.6,
                'fat' => 5.1,
                'saturatedFat' => 0.8,
                'transFat' => 50.7,
                'cholesterol' => 0.0,
                'carbohydrate' => 9.7,
                'sugar' => 0.9,
                'dietaryFiber' => 4.6,
                'sodium' => 697.0,
                'calcium' => 15.0,
                'potassium' => 354.0,
                'ferrum' => 1.7,
                'photo' => 'http://120.110.112.96/qrfood/img/24.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:52',
            ),
            24 => 
            array (
                
                'rsId' => 1,
                'fdName' => '海帶絲',
                'cId' => 1,
                'gram' => 64.0,
                'calorie' => 14.0,
                'protein' => 0.4,
                'fat' => 0.1,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 3.2,
                'sugar' => 0.0,
                'dietaryFiber' => 1.8,
                'sodium' => 786.0,
                'calcium' => 36.0,
                'potassium' => 8.0,
                'ferrum' => 0.6,
                'photo' => 'http://120.110.112.96/qrfood/img/25.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:54',
            ),
            25 => 
            array (
                
                'rsId' => 1,
                'fdName' => '炸春捲',
                'cId' => 4,
                'gram' => 33.0,
                'calorie' => 178.0,
                'protein' => 1.7,
                'fat' => 14.6,
                'saturatedFat' => 2.5,
                'transFat' => 101.4,
                'cholesterol' => 0.0,
                'carbohydrate' => 10.4,
                'sugar' => 0.0,
                'dietaryFiber' => 0.9,
                'sodium' => 148.0,
                'calcium' => 0.0,
                'potassium' => 38.0,
                'ferrum' => 0.4,
                'photo' => 'http://120.110.112.96/qrfood/img/26.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:34:57',
            ),
            26 => 
            array (
                
                'rsId' => 1,
                'fdName' => '涼拌筍子',
                'cId' => 1,
                'gram' => 60.0,
                'calorie' => 28.0,
                'protein' => 1.6,
                'fat' => 0.0,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 5.7,
                'sugar' => 1.7,
                'dietaryFiber' => 1.5,
                'sodium' => 26.0,
                'calcium' => 24.0,
                'potassium' => 250.0,
                'ferrum' => 0.2,
                'photo' => 'http://120.110.112.96/qrfood/img/27.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:01',
            ),
            27 => 
            array (
                
                'rsId' => 1,
                'fdName' => '拌炒豆腐',
                'cId' => 2,
                'gram' => 59.0,
                'calorie' => 54.0,
                'protein' => 5.2,
                'fat' => 2.0,
                'saturatedFat' => 0.6,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 3.8,
                'sugar' => 0.0,
                'dietaryFiber' => 0.4,
                'sodium' => 101.0,
                'calcium' => 83.0,
                'potassium' => 114.0,
                'ferrum' => 1.2,
                'photo' => 'http://120.110.112.96/qrfood/img/28.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:03',
            ),
            28 => 
            array (
                
                'rsId' => 1,
                'fdName' => '豬血',
                'cId' => 2,
                'gram' => 64.0,
                'calorie' => 61.0,
                'protein' => 3.8,
                'fat' => 5.2,
                'saturatedFat' => 0.9,
                'transFat' => 50.7,
                'cholesterol' => 30.0,
                'carbohydrate' => 0.5,
                'sugar' => 0.1,
                'dietaryFiber' => 0.0,
                'sodium' => 796.0,
                'calcium' => 6.0,
                'potassium' => 24.0,
                'ferrum' => 16.9,
                'photo' => 'http://120.110.112.96/qrfood/img/29.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:05',
            ),
            29 => 
            array (
                
                'rsId' => 1,
                'fdName' => '糖醋排骨',
                'cId' => 2,
                'gram' => 105.0,
                'calorie' => 141.0,
                'protein' => 7.6,
                'fat' => 10.9,
                'saturatedFat' => 3.2,
                'transFat' => 50.7,
                'cholesterol' => 13.0,
                'carbohydrate' => 2.7,
                'sugar' => 0.3,
                'dietaryFiber' => 0.1,
                'sodium' => 711.0,
                'calcium' => 14.0,
                'potassium' => 141.0,
                'ferrum' => 0.6,
                'photo' => 'http://120.110.112.96/qrfood/img/30.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:07',
            ),
            30 => 
            array (
                
                'rsId' => 1,
                'fdName' => '豬耳朵',
                'cId' => 2,
                'gram' => 49.0,
                'calorie' => 114.0,
                'protein' => 11.9,
                'fat' => 7.1,
                'saturatedFat' => 2.5,
                'transFat' => 0.0,
                'cholesterol' => 48.0,
                'carbohydrate' => 0.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 775.0,
                'calcium' => 10.0,
                'potassium' => 25.0,
                'ferrum' => 0.7,
                'photo' => 'http://120.110.112.96/qrfood/img/31.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:10',
            ),
            31 => 
            array (
                
                'rsId' => 1,
                'fdName' => '麻油雞',
                'cId' => 2,
                'gram' => 58.0,
                'calorie' => 126.0,
                'protein' => 10.1,
                'fat' => 8.9,
                'saturatedFat' => 2.2,
                'transFat' => 0.0,
                'cholesterol' => 50.0,
                'carbohydrate' => 0.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 719.0,
                'calcium' => 5.0,
                'potassium' => 105.5,
                'ferrum' => 0.6,
                'photo' => 'http://120.110.112.96/qrfood/img/32.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:12',
            ),
            32 => 
            array (
                
                'rsId' => 1,
                'fdName' => '蜜汁里肌',
                'cId' => 2,
                'gram' => 62.0,
                'calorie' => 68.0,
                'protein' => 14.6,
                'fat' => 0.4,
                'saturatedFat' => 0.1,
                'transFat' => 0.0,
                'cholesterol' => 32.0,
                'carbohydrate' => 0.6,
                'sugar' => 0.1,
                'dietaryFiber' => 0.0,
                'sodium' => 87.0,
                'calcium' => 2.0,
                'potassium' => 216.0,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/33.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:14',
            ),
            33 => 
            array (
                
                'rsId' => 1,
                'fdName' => '香雞排',
                'cId' => 2,
                'gram' => 113.0,
                'calorie' => 216.0,
                'protein' => 12.0,
                'fat' => 18.5,
                'saturatedFat' => 4.2,
                'transFat' => 101.4,
                'cholesterol' => 46.0,
                'carbohydrate' => 0.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 60.0,
                'calcium' => 4.0,
                'potassium' => 174.0,
                'ferrum' => 0.6,
                'photo' => 'http://120.110.112.96/qrfood/img/34.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:17',
            ),
            34 => 
            array (
                
                'rsId' => 1,
                'fdName' => '滷豬排',
                'cId' => 2,
                'gram' => 124.0,
                'calorie' => 275.0,
                'protein' => 21.7,
                'fat' => 20.2,
                'saturatedFat' => 6.7,
                'transFat' => 50.7,
                'cholesterol' => 95.0,
                'carbohydrate' => 0.3,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 216.0,
                'calcium' => 49.0,
                'potassium' => 361.0,
                'ferrum' => 1.6,
                'photo' => 'http://120.110.112.96/qrfood/img/35.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:20',
            ),
            35 => 
            array (
                
                'rsId' => 1,
                'fdName' => '椒麻雞腿',
                'cId' => 2,
                'gram' => 175.0,
                'calorie' => 190.0,
                'protein' => 21.2,
                'fat' => 10.9,
                'saturatedFat' => 2.4,
                'transFat' => 50.7,
                'cholesterol' => 43.0,
                'carbohydrate' => 0.5,
                'sugar' => 0.1,
                'dietaryFiber' => 0.1,
                'sodium' => 268.0,
                'calcium' => 2.0,
                'potassium' => 266.0,
                'ferrum' => 0.7,
                'photo' => 'http://l120.110.112.96/qrfood/img/36.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:26',
            ),
            36 => 
            array (
                
                'rsId' => 1,
                'fdName' => '紅燒鯖魚',
                'cId' => 2,
                'gram' => 149.0,
                'calorie' => 571.0,
                'protein' => 26.2,
                'fat' => 51.7,
                'saturatedFat' => 12.0,
                'transFat' => 50.7,
                'cholesterol' => 83.0,
                'carbohydrate' => 0.6,
                'sugar' => 0.1,
                'dietaryFiber' => 0.1,
                'sodium' => 212.0,
                'calcium' => 22.0,
                'potassium' => 571.0,
                'ferrum' => 2.8,
                'photo' => 'http://120.110.112.96/qrfood/img/37.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:29',
            ),
            37 => 
            array (
                
                'rsId' => 1,
                'fdName' => '韓式泡菜燒肉',
                'cId' => 2,
                'gram' => 82.0,
                'calorie' => 176.0,
                'protein' => 11.7,
                'fat' => 13.5,
                'saturatedFat' => 4.1,
                'transFat' => 50.7,
                'cholesterol' => 47.0,
                'carbohydrate' => 1.4,
                'sugar' => 0.2,
                'dietaryFiber' => 0.7,
                'sodium' => 817.0,
                'calcium' => 17.0,
                'potassium' => 273.0,
                'ferrum' => 1.1,
                'photo' => 'http://120.110.112.96/qrfood/img/38.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:31',
            ),
            38 => 
            array (
                
                'rsId' => 1,
                'fdName' => '油雞',
                'cId' => 2,
                'gram' => 66.0,
                'calorie' => 79.0,
                'protein' => 15.3,
                'fat' => 1.4,
                'saturatedFat' => 0.4,
                'transFat' => 0.0,
                'cholesterol' => 40.0,
                'carbohydrate' => 0.3,
                'sugar' => 0.2,
                'dietaryFiber' => 0.0,
                'sodium' => 133.0,
                'calcium' => 4.0,
                'potassium' => 215.0,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/39.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:33',
            ),
            39 => 
            array (
                
                'rsId' => 1,
                'fdName' => '香辣雞米花',
                'cId' => 2,
                'gram' => 56.0,
                'calorie' => 164.0,
                'protein' => 9.8,
                'fat' => 13.6,
                'saturatedFat' => 2.9,
                'transFat' => 50.7,
                'cholesterol' => 48.0,
                'carbohydrate' => 0.3,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 29.0,
                'calcium' => 3.0,
                'potassium' => 101.0,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/40.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:36',
            ),
            40 => 
            array (
                
                'rsId' => 1,
                'fdName' => '紅燒獅子頭',
                'cId' => 2,
                'gram' => 90.0,
                'calorie' => 236.0,
                'protein' => 15.8,
                'fat' => 18.7,
                'saturatedFat' => 4.1,
                'transFat' => 50.7,
                'cholesterol' => 77.0,
                'carbohydrate' => 0.3,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 146.0,
                'calcium' => 5.0,
                'potassium' => 162.0,
                'ferrum' => 0.8,
                'photo' => 'http://120.110.112.96/qrfood/img/41.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:39',
            ),
            41 => 
            array (
                
                'rsId' => 1,
                'fdName' => '花枝排',
                'cId' => 2,
                'gram' => 85.0,
                'calorie' => 247.0,
                'protein' => 4.7,
                'fat' => 16.2,
                'saturatedFat' => 3.9,
                'transFat' => 101.4,
                'cholesterol' => 15.0,
                'carbohydrate' => 21.2,
                'sugar' => 2.7,
                'dietaryFiber' => 1.1,
                'sodium' => 551.0,
                'calcium' => 17.0,
                'potassium' => 105.0,
                'ferrum' => 0.7,
                'photo' => 'http://120.110.112.96/qrfood/img/42.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:42',
            ),
            42 => 
            array (
                
                'rsId' => 1,
                'fdName' => '起司豬排',
                'cId' => 2,
                'gram' => 100.0,
                'calorie' => 347.0,
                'protein' => 21.9,
                'fat' => 27.9,
                'saturatedFat' => 10.4,
                'transFat' => 101.4,
                'cholesterol' => 96.0,
                'carbohydrate' => 1.3,
                'sugar' => 0.4,
                'dietaryFiber' => 1.9,
                'sodium' => 448.0,
                'calcium' => 174.0,
                'potassium' => 309.0,
                'ferrum' => 1.5,
                'photo' => 'http://120.110.112.96/qrfood/img/43.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:44',
            ),
            43 => 
            array (
                
                'rsId' => 1,
                'fdName' => '香蔥肉燥',
                'cId' => 2,
                'gram' => 81.0,
                'calorie' => 203.0,
                'protein' => 3.8,
                'fat' => 20.2,
                'saturatedFat' => 6.5,
                'transFat' => 50.7,
                'cholesterol' => 44.0,
                'carbohydrate' => 1.7,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 376.0,
                'calcium' => 4.0,
                'potassium' => 118.0,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/44.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:46',
            ),
            44 => 
            array (
                
                'rsId' => 1,
                'fdName' => '咖哩雞排',
                'cId' => 2,
                'gram' => 89.0,
                'calorie' => 220.0,
                'protein' => 15.6,
                'fat' => 16.3,
                'saturatedFat' => 4.1,
                'transFat' => 50.7,
                'cholesterol' => 59.0,
                'carbohydrate' => 1.8,
                'sugar' => 0.0,
                'dietaryFiber' => 1.1,
                'sodium' => 94.0,
                'calcium' => 28.0,
                'potassium' => 274.0,
                'ferrum' => 2.8,
                'photo' => 'http://120.110.112.96/qrfood/img/45.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:48',
            ),
            45 => 
            array (
                
                'rsId' => 1,
                'fdName' => '椒麻豬排',
                'cId' => 2,
                'gram' => 125.0,
                'calorie' => 325.0,
                'protein' => 21.6,
                'fat' => 25.3,
                'saturatedFat' => 7.5,
                'transFat' => 101.4,
                'cholesterol' => 95.0,
                'carbohydrate' => 1.4,
                'sugar' => 0.0,
                'dietaryFiber' => 0.1,
                'sodium' => 242.0,
                'calcium' => 50.0,
                'potassium' => 367.0,
                'ferrum' => 1.7,
                'photo' => 'http://120.110.112.96/qrfood/img/46.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:51',
            ),
            46 => 
            array (
                
                'rsId' => 1,
                'fdName' => '雙醬雞肉捲',
                'cId' => 2,
                'gram' => 127.0,
                'calorie' => 356.0,
                'protein' => 21.4,
                'fat' => 28.7,
                'saturatedFat' => 6.2,
                'transFat' => 101.4,
                'cholesterol' => 106.0,
                'carbohydrate' => 2.1,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 225.0,
                'calcium' => 8.0,
                'potassium' => 225.0,
                'ferrum' => 1.2,
                'photo' => 'http://120.110.112.96/qrfood/img/47.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:54',
            ),
            47 => 
            array (
                
                'rsId' => 1,
                'fdName' => '韓式腿排',
                'cId' => 2,
                'gram' => 76.0,
                'calorie' => 183.0,
                'protein' => 13.0,
                'fat' => 14.3,
                'saturatedFat' => 3.6,
                'transFat' => 50.7,
                'cholesterol' => 50.0,
                'carbohydrate' => 0.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 65.0,
                'calcium' => 5.0,
                'potassium' => 189.0,
                'ferrum' => 0.7,
                'photo' => 'http://120.110.112.96/qrfood/img/48.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:57',
            ),
            48 => 
            array (
                
                'rsId' => 1,
                'fdName' => '隔間肉',
                'cId' => 2,
                'gram' => 67.0,
                'calorie' => 172.0,
                'protein' => 9.3,
                'fat' => 14.7,
                'saturatedFat' => 4.8,
                'transFat' => 50.7,
                'cholesterol' => 51.0,
                'carbohydrate' => 0.7,
                'sugar' => 0.0,
                'dietaryFiber' => 0.6,
                'sodium' => 28.0,
                'calcium' => 4.0,
                'potassium' => 178.0,
                'ferrum' => 1.8,
                'photo' => 'http://120.110.112.96/qrfood/img/49.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:35:59',
            ),
            49 => 
            array (
                
                'rsId' => 1,
                'fdName' => '香辣雞丁',
                'cId' => 2,
                'gram' => 79.0,
                'calorie' => 207.0,
                'protein' => 13.3,
                'fat' => 16.7,
                'saturatedFat' => 3.7,
                'transFat' => 50.7,
                'cholesterol' => 66.0,
                'carbohydrate' => 0.2,
                'sugar' => 0.1,
                'dietaryFiber' => 0.1,
                'sodium' => 728.0,
                'calcium' => 7.0,
                'potassium' => 142.0,
                'ferrum' => 0.9,
                'photo' => 'http://120.110.112.96/qrfood/img/50.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:36:03',
            ),
            50 => 
            array (
                
                'rsId' => 1,
                'fdName' => '花枝條',
                'cId' => 2,
                'gram' => 88.0,
                'calorie' => 140.0,
                'protein' => 10.6,
                'fat' => 10.5,
                'saturatedFat' => 1.8,
                'transFat' => 101.4,
                'cholesterol' => 164.0,
                'carbohydrate' => 3.9,
                'sugar' => 0.0,
                'dietaryFiber' => 0.1,
                'sodium' => 58.0,
                'calcium' => 9.0,
                'potassium' => 82.0,
                'ferrum' => 0.1,
                'photo' => 'http://120.110.112.96/qrfood/img/51.jpg',
                'disable' => 0,
                'created_at' => '2019-08-22 14:45:00',
                'updated_at' => '2019-10-17 16:36:06',
            ),
            51 => 
            array (
                
                'rsId' => 2,
                'fdName' => '炒菇類',
                'cId' => 1,
                'gram' => 85.0,
                'calorie' => 41.3,
                'protein' => 2.5,
                'fat' => 1.4,
                'saturatedFat' => 0.2,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 5.5,
                'sugar' => 0.2,
                'dietaryFiber' => 1.9,
                'sodium' => 28.5,
                'calcium' => 3.1,
                'potassium' => 380.4,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 14:30:09',
                'updated_at' => '2019-12-01 14:30:09',
            ),
            52 => 
            array (
                
                'rsId' => 2,
                'fdName' => '炒胡瓜',
                'cId' => 1,
                'gram' => 80.0,
                'calorie' => 48.1,
                'protein' => 1.3,
                'fat' => 3.8,
                'saturatedFat' => 0.7,
                'transFat' => 0.0,
                'cholesterol' => 1.2,
                'carbohydrate' => 2.3,
                'sugar' => 0.05,
                'dietaryFiber' => 0.5,
                'sodium' => 275.8,
                'calcium' => 10.3,
                'potassium' => 386.5,
                'ferrum' => 1.4,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 14:32:39',
                'updated_at' => '2019-12-01 14:33:23',
            ),
            53 => 
            array (
                
                'rsId' => 1,
                'fdName' => '拌炒筊白筍',
                'cId' => 1,
                'gram' => 55.0,
                'calorie' => 54.7,
                'protein' => 4.9,
                'fat' => 3.1,
                'saturatedFat' => 0.8,
                'transFat' => 0.0,
                'cholesterol' => 17.0,
                'carbohydrate' => 1.0,
                'sugar' => 0.4,
                'dietaryFiber' => 0.5,
                'sodium' => 34.4,
                'calcium' => 2.4,
                'potassium' => 97.6,
                'ferrum' => 0.2,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 14:44:57',
                'updated_at' => '2019-12-01 14:45:17',
            ),
            54 => 
            array (
                
                'rsId' => 2,
                'fdName' => '拌炒筊白筍',
                'cId' => 1,
                'gram' => 55.0,
                'calorie' => 54.7,
                'protein' => 4.9,
                'fat' => 3.1,
                'saturatedFat' => 0.8,
                'transFat' => 0.0,
                'cholesterol' => 17.0,
                'carbohydrate' => 1.0,
                'sugar' => 0.4,
                'dietaryFiber' => 0.5,
                'sodium' => 34.4,
                'calcium' => 2.4,
                'potassium' => 97.6,
                'ferrum' => 0.2,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 14:46:18',
                'updated_at' => '2019-12-01 14:46:18',
            ),
            55 => 
            array (
                
                'rsId' => 2,
                'fdName' => '番茄炒蛋',
                'cId' => 1,
                'gram' => 85.0,
                'calorie' => 82.8,
                'protein' => 7.2,
                'fat' => 5.0,
                'saturatedFat' => 1.7,
                'transFat' => 0.0,
                'cholesterol' => 212.5,
                'carbohydrate' => 2.3,
                'sugar' => 0.7,
                'dietaryFiber' => 0.2,
                'sodium' => 77.8,
                'calcium' => 25.8,
                'potassium' => 139.6,
                'ferrum' => 1.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 14:48:50',
                'updated_at' => '2019-12-01 14:48:50',
            ),
            56 => 
            array (
                
                'rsId' => 2,
                'fdName' => '炒南瓜',
                'cId' => 1,
                'gram' => 75.0,
                'calorie' => 56.4,
                'protein' => 1.4,
                'fat' => 0.0,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 13.0,
                'sugar' => 0.0,
                'dietaryFiber' => 1.6,
                'sodium' => 65.3,
                'calcium' => 10.2,
                'potassium' => 739.8,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 14:53:04',
                'updated_at' => '2020-04-24 15:34:54',
            ),
            57 => 
            array (
                
                'rsId' => 2,
                'fdName' => '番茄炒豆腐',
                'cId' => 4,
                'gram' => 120.0,
                'calorie' => 65.0,
                'protein' => 4.2,
                'fat' => 2.1,
                'saturatedFat' => 0.3,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 6.9,
                'sugar' => 0.6,
                'dietaryFiber' => 0.99,
                'sodium' => 61.4,
                'calcium' => 12.8,
                'potassium' => 203.2,
                'ferrum' => 1.2,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 14:54:22',
                'updated_at' => '2019-12-01 14:54:22',
            ),
            58 => 
            array (
                
                'rsId' => 2,
                'fdName' => '苦瓜小魚乾',
                'cId' => 4,
                'gram' => 70.0,
                'calorie' => 21.3,
                'protein' => 1.7,
                'fat' => 0.1,
                'saturatedFat' => 0.1,
                'transFat' => 0.0,
                'cholesterol' => 3.5,
                'carbohydrate' => 3.4,
                'sugar' => 0.3,
                'dietaryFiber' => 2.0,
                'sodium' => 351.0,
                'calcium' => 25.4,
                'potassium' => 218.6,
                'ferrum' => 0.4,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 14:58:20',
                'updated_at' => '2019-12-01 14:58:20',
            ),
            59 => 
            array (
                
                'rsId' => 2,
                'fdName' => '苦瓜鹹蛋',
                'cId' => 4,
                'gram' => 70.0,
                'calorie' => 24.2,
                'protein' => 1.3,
                'fat' => 0.8,
                'saturatedFat' => 0.3,
                'transFat' => 0.0,
                'cholesterol' => 31.7,
                'carbohydrate' => 3.0,
                'sugar' => 0.2,
                'dietaryFiber' => 1.9,
                'sodium' => 92.8,
                'calcium' => 15.7,
                'potassium' => 134.8,
                'ferrum' => 0.4,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:00:03',
                'updated_at' => '2019-12-01 15:00:03',
            ),
            60 => 
            array (
                
                'rsId' => 2,
                'fdName' => '玉米筍鳥蛋',
                'cId' => 4,
                'gram' => 65.0,
                'calorie' => 43.9,
                'protein' => 3.9,
                'fat' => 1.2,
                'saturatedFat' => 0.4,
                'transFat' => 0.0,
                'cholesterol' => 63.0,
                'carbohydrate' => 4.3,
                'sugar' => 1.4,
                'dietaryFiber' => 1.0,
                'sodium' => 166.4,
                'calcium' => 15.3,
                'potassium' => 376.1,
                'ferrum' => 1.1,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:00:57',
                'updated_at' => '2019-12-01 15:00:57',
            ),
            61 => 
            array (
                
                'rsId' => 2,
                'fdName' => '芋頭排骨',
                'cId' => 4,
                'gram' => 70.0,
                'calorie' => 141.3,
                'protein' => 9.93,
                'fat' => 8.5,
                'saturatedFat' => 2.3,
                'transFat' => 0.0,
                'cholesterol' => 34.5,
                'carbohydrate' => 14.7,
                'sugar' => 0.4,
                'dietaryFiber' => 0.7,
                'sodium' => 205.8,
                'calcium' => 10.1,
                'potassium' => 257.3,
                'ferrum' => 1.0,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:01:44',
                'updated_at' => '2019-12-01 15:01:44',
            ),
            62 => 
            array (
                
                'rsId' => 2,
                'fdName' => '糖醋排骨',
                'cId' => 1,
                'gram' => 70.0,
                'calorie' => 135.2,
                'protein' => 10.9,
                'fat' => 8.2,
                'saturatedFat' => 3.0,
                'transFat' => 0.0,
                'cholesterol' => 41.4,
                'carbohydrate' => 3.7,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 77.4,
                'calcium' => 2.1,
                'potassium' => 325.0,
                'ferrum' => 0.8,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:02:25',
                'updated_at' => '2019-12-01 15:02:25',
            ),
            63 => 
            array (
                
                'rsId' => 2,
                'fdName' => '醬油魚柳',
                'cId' => 2,
                'gram' => 70.0,
                'calorie' => 99.2,
                'protein' => 12.9,
                'fat' => 3.5,
                'saturatedFat' => 0.8,
                'transFat' => 0.0,
                'cholesterol' => 33.9,
                'carbohydrate' => 13.7,
                'sugar' => 0.2,
                'dietaryFiber' => 0.4,
                'sodium' => 251.1,
                'calcium' => 46.7,
                'potassium' => 138.1,
                'ferrum' => 0.2,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:03:05',
                'updated_at' => '2019-12-01 15:03:05',
            ),
            64 => 
            array (
                
                'rsId' => 2,
                'fdName' => '糖醋魚柳',
                'cId' => 2,
                'gram' => 70.0,
                'calorie' => 82.9,
                'protein' => 14.7,
                'fat' => 1.7,
                'saturatedFat' => 0.5,
                'transFat' => 0.0,
                'cholesterol' => 33.9,
                'carbohydrate' => 3.6,
                'sugar' => 2.8,
                'dietaryFiber' => 0.1,
                'sodium' => 82.1,
                'calcium' => 40.6,
                'potassium' => 227.0,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:03:41',
                'updated_at' => '2019-12-01 15:03:41',
            ),
            65 => 
            array (
                
                'rsId' => 2,
                'fdName' => '洋蔥五花肉',
                'cId' => 2,
                'gram' => 70.0,
                'calorie' => 214.0,
                'protein' => 7.7,
                'fat' => 19.3,
                'saturatedFat' => 0.3,
                'transFat' => 0.0,
                'cholesterol' => 34.0,
                'carbohydrate' => 1.6,
                'sugar' => 0.0,
                'dietaryFiber' => 0.2,
                'sodium' => 41.0,
                'calcium' => 4.3,
                'potassium' => 116.7,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:04:16',
                'updated_at' => '2019-12-01 15:04:16',
            ),
            66 => 
            array (
                
                'rsId' => 2,
                'fdName' => '黑木耳五花肉',
                'cId' => 2,
                'gram' => 70.0,
                'calorie' => 213.7,
                'protein' => 7.7,
                'fat' => 19.3,
                'saturatedFat' => 0.3,
                'transFat' => 0.0,
                'cholesterol' => 34.0,
                'carbohydrate' => 1.5,
                'sugar' => 0.0,
                'dietaryFiber' => 0.77,
                'sodium' => 42.0,
                'calcium' => 4.6,
                'potassium' => 112.1,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:04:50',
                'updated_at' => '2019-12-01 15:04:50',
            ),
            67 => 
            array (
                
                'rsId' => 2,
                'fdName' => '泡菜五花肉',
                'cId' => 2,
                'gram' => 70.0,
                'calorie' => 213.2,
                'protein' => 7.8,
                'fat' => 34.8,
                'saturatedFat' => 0.3,
                'transFat' => 0.0,
                'cholesterol' => 35.8,
                'carbohydrate' => 1.2,
                'sugar' => 0.04,
                'dietaryFiber' => 0.2,
                'sodium' => 79.8,
                'calcium' => 5.6,
                'potassium' => 127.9,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:05:27',
                'updated_at' => '2019-12-01 15:05:27',
            ),
            68 => 
            array (
                
                'rsId' => 2,
                'fdName' => '沙拉',
                'cId' => 1,
                'gram' => 100.0,
                'calorie' => 226.5,
                'protein' => 3.4,
                'fat' => 17.8,
                'saturatedFat' => 2.8,
                'transFat' => 0.0,
                'cholesterol' => 47.4,
                'carbohydrate' => 13.2,
                'sugar' => 0.03,
                'dietaryFiber' => 0.8,
                'sodium' => 265.9,
                'calcium' => 9.2,
                'potassium' => 281.9,
                'ferrum' => 0.7,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:06:07',
                'updated_at' => '2019-12-01 15:06:07',
            ),
            69 => 
            array (
                
                'rsId' => 2,
                'fdName' => '高麗菜',
                'cId' => 1,
                'gram' => 100.0,
                'calorie' => 23.8,
                'protein' => 1.3,
                'fat' => 0.1,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 4.7,
                'sugar' => 0.0,
                'dietaryFiber' => 1.2,
                'sodium' => 12.1,
                'calcium' => 45.6,
                'potassium' => 179.3,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:06:39',
                'updated_at' => '2019-12-01 15:06:39',
            ),
            70 => 
            array (
                
                'rsId' => 2,
                'fdName' => '萵苣',
                'cId' => 1,
                'gram' => 100.0,
                'calorie' => 16.2,
                'protein' => 1.0,
                'fat' => 0.1,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 3.1,
                'sugar' => 0.0,
                'dietaryFiber' => 1.2,
                'sodium' => 22.0,
                'calcium' => 16.0,
                'potassium' => 310.0,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:07:08',
                'updated_at' => '2019-12-01 15:07:08',
            ),
            71 => 
            array (
                
                'rsId' => 2,
                'fdName' => '油菜',
                'cId' => 1,
                'gram' => 100.0,
                'calorie' => 13.7,
                'protein' => 1.6,
                'fat' => 0.2,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 1.8,
                'sugar' => 0.0,
                'dietaryFiber' => 1.2,
                'sodium' => 94.3,
                'calcium' => 99.9,
                'potassium' => 289.7,
                'ferrum' => 2.5,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:07:44',
                'updated_at' => '2019-12-01 15:07:44',
            ),
            72 => 
            array (
                
                'rsId' => 2,
                'fdName' => '莧菜',
                'cId' => 1,
                'gram' => 100.0,
                'calorie' => 40.6,
                'protein' => 6.3,
                'fat' => 0.6,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 4.9,
                'sugar' => 0.0,
                'dietaryFiber' => 4.2,
                'sodium' => 20.1,
                'calcium' => 146.2,
                'potassium' => 507.4,
                'ferrum' => 4.6,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:08:30',
                'updated_at' => '2019-12-01 15:08:30',
            ),
            73 => 
            array (
                
                'rsId' => 2,
                'fdName' => '菠菜',
                'cId' => 1,
                'gram' => 100.0,
                'calorie' => 19.4,
                'protein' => 2.0,
                'fat' => 0.3,
                'saturatedFat' => 0.0,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 2.8,
                'sugar' => 0.0,
                'dietaryFiber' => 2.0,
                'sodium' => 53.4,
                'calcium' => 82.7,
                'potassium' => 499.9,
                'ferrum' => 3.2,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:08:57',
                'updated_at' => '2019-12-01 15:08:57',
            ),
            74 => 
            array (
                
                'rsId' => 2,
                'fdName' => '洋蔥培根',
                'cId' => 2,
                'gram' => 65.0,
                'calorie' => 120.1,
                'protein' => 4.1,
                'fat' => 9.7,
                'saturatedFat' => 3.6,
                'transFat' => 0.0,
                'cholesterol' => 15.8,
                'carbohydrate' => 3.8,
                'sugar' => 0.0,
                'dietaryFiber' => 0.8,
                'sodium' => 251.3,
                'calcium' => 8.3,
                'potassium' => 594.5,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:09:30',
                'updated_at' => '2019-12-01 15:09:30',
            ),
            75 => 
            array (
                
                'rsId' => 2,
                'fdName' => '木耳杏鮑菇',
                'cId' => 1,
                'gram' => 80.0,
                'calorie' => 40.9,
                'protein' => 4.0,
                'fat' => 0.3,
                'saturatedFat' => 0.1,
                'transFat' => 0.0,
                'cholesterol' => 12.0,
                'carbohydrate' => 101.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.6,
                'sodium' => 93.9,
                'calcium' => 9.4,
                'potassium' => 651.4,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:10:02',
                'updated_at' => '2019-12-01 15:10:02',
            ),
            76 => 
            array (
                
                'rsId' => 2,
                'fdName' => '滷蛋',
                'cId' => 2,
                'gram' => 55.0,
                'calorie' => 103.7,
                'protein' => 8.5,
                'fat' => 6.1,
                'saturatedFat' => 2.2,
                'transFat' => 0.0,
                'cholesterol' => 264.3,
                'carbohydrate' => 3.6,
                'sugar' => 2.5,
                'dietaryFiber' => 0.0,
                'sodium' => 323.7,
                'calcium' => 33.2,
                'potassium' => 87.2,
                'ferrum' => 1.5,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:10:39',
                'updated_at' => '2019-12-01 15:10:39',
            ),
            77 => 
            array (
                
                'rsId' => 2,
                'fdName' => '水餃',
                'cId' => 4,
                'gram' => 55.0,
                'calorie' => 135.9,
                'protein' => 3.9,
                'fat' => 7.0,
                'saturatedFat' => 2.5,
                'transFat' => 0.0,
                'cholesterol' => 9.5,
                'carbohydrate' => 143.0,
                'sugar' => 0.0,
                'dietaryFiber' => 1.1,
                'sodium' => 183.1,
                'calcium' => 4.3,
                'potassium' => 88.0,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:11:11',
                'updated_at' => '2019-12-01 15:11:11',
            ),
            78 => 
            array (
                
                'rsId' => 2,
                'fdName' => '豆干',
                'cId' => 2,
                'gram' => 45.0,
                'calorie' => 72.1,
                'protein' => 7.8,
                'fat' => 3.8,
                'saturatedFat' => 0.5,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 1.5,
                'sugar' => 0.0,
                'dietaryFiber' => 1.4,
                'sodium' => 52.0,
                'calcium' => 287.9,
                'potassium' => 74.8,
                'ferrum' => 2.0,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:11:45',
                'updated_at' => '2019-12-01 15:11:45',
            ),
            79 => 
            array (
                
                'rsId' => 2,
                'fdName' => '油豆腐',
                'cId' => 1,
                'gram' => 35.0,
                'calorie' => 48.1,
                'protein' => 4.4,
                'fat' => 3.1,
                'saturatedFat' => 0.5,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 0.5,
                'sugar' => 0.0,
                'dietaryFiber' => 0.2,
                'sodium' => 0.3,
                'calcium' => 75.4,
                'potassium' => 68.7,
                'ferrum' => 0.9,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:13:09',
                'updated_at' => '2019-12-01 15:13:09',
            ),
            80 => 
            array (
                
                'rsId' => 2,
                'fdName' => '甜不辣與米腸',
                'cId' => 4,
                'gram' => 100.0,
                'calorie' => 185.1,
                'protein' => 10.5,
                'fat' => 4.9,
                'saturatedFat' => 1.3,
                'transFat' => 0.0,
                'cholesterol' => 18.1,
                'carbohydrate' => 24.7,
                'sugar' => 0.0,
                'dietaryFiber' => 0.3,
                'sodium' => 578.1,
                'calcium' => 13.7,
                'potassium' => 109.9,
                'ferrum' => 1.2,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:13:47',
                'updated_at' => '2019-12-01 15:13:47',
            ),
            81 => 
            array (
                
                'rsId' => 2,
                'fdName' => '炸豬塊',
                'cId' => 2,
                'gram' => 75.0,
                'calorie' => 192.7,
                'protein' => 12.2,
                'fat' => 15.5,
                'saturatedFat' => 4.4,
                'transFat' => 0.0,
                'cholesterol' => 47.0,
                'carbohydrate' => 0.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 37.0,
                'calcium' => 2.2,
                'potassium' => 179.0,
                'ferrum' => 0.5,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:14:16',
                'updated_at' => '2019-12-01 15:14:16',
            ),
            82 => 
            array (
                
                'rsId' => 2,
                'fdName' => '薯餅',
                'cId' => 4,
                'gram' => 70.0,
                'calorie' => 282.6,
                'protein' => 2.6,
                'fat' => 13.8,
                'saturatedFat' => 3.5,
                'transFat' => 0.0,
                'cholesterol' => 3.3,
                'carbohydrate' => 37.2,
                'sugar' => 0.0,
                'dietaryFiber' => 1.0,
                'sodium' => 16.2,
                'calcium' => 11.5,
                'potassium' => 132.9,
                'ferrum' => 0.9,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:14:52',
                'updated_at' => '2019-12-01 15:14:52',
            ),
            83 => 
            array (
                
                'rsId' => 2,
            'fdName' => '麥克雞塊(大)',
                'cId' => 2,
                'gram' => 60.0,
                'calorie' => 173.2,
                'protein' => 8.3,
                'fat' => 12.6,
                'saturatedFat' => 4.1,
                'transFat' => 0.0,
                'cholesterol' => 17.9,
                'carbohydrate' => 6.6,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 324.1,
                'calcium' => 3.7,
                'potassium' => 108.8,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:15:28',
                'updated_at' => '2019-12-01 15:15:28',
            ),
            84 => 
            array (
                
                'rsId' => 2,
                'fdName' => '炸雞排',
                'cId' => 2,
                'gram' => 65.0,
                'calorie' => 172.9,
                'protein' => 9.0,
                'fat' => 14.8,
                'saturatedFat' => 3.8,
                'transFat' => 0.0,
                'cholesterol' => 44.3,
                'carbohydrate' => 0.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 44.6,
                'calcium' => 4.8,
                'potassium' => 147.2,
                'ferrum' => 0.6,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:16:00',
                'updated_at' => '2019-12-01 15:16:00',
            ),
            85 => 
            array (
                
                'rsId' => 2,
                'fdName' => '煎雞腿排',
                'cId' => 2,
                'gram' => 45.0,
                'calorie' => 111.6,
                'protein' => 6.3,
                'fat' => 9.3,
                'saturatedFat' => 2.5,
                'transFat' => 0.0,
                'cholesterol' => 31.1,
                'carbohydrate' => 0.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 31.5,
                'calcium' => 3.4,
                'potassium' => 73.0,
                'ferrum' => 0.4,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:16:30',
                'updated_at' => '2019-12-01 15:16:30',
            ),
            86 => 
            array (
                
                'rsId' => 2,
                'fdName' => '炸鱈魚',
                'cId' => 2,
                'gram' => 95.0,
                'calorie' => 244.1,
                'protein' => 11.3,
                'fat' => 21.7,
                'saturatedFat' => 2.4,
                'transFat' => 0.0,
                'cholesterol' => 57.9,
                'carbohydrate' => 0.9,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 54.2,
                'calcium' => 5.3,
                'potassium' => 261.9,
                'ferrum' => 0.1,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:17:06',
                'updated_at' => '2019-12-01 15:17:06',
            ),
            87 => 
            array (
                
                'rsId' => 2,
                'fdName' => '起士豬排',
                'cId' => 2,
                'gram' => 80.0,
                'calorie' => 305.6,
                'protein' => 15.9,
                'fat' => 18.2,
                'saturatedFat' => 1.1,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 19.5,
                'sugar' => 0.0,
                'dietaryFiber' => 0.0,
                'sodium' => 477.2,
                'calcium' => 56.3,
                'potassium' => 213.5,
                'ferrum' => 0.9,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:17:41',
                'updated_at' => '2019-12-01 15:17:41',
            ),
            88 => 
            array (
                
                'rsId' => 2,
                'fdName' => '地瓜葉',
                'cId' => 1,
                'gram' => 102.0,
                'calorie' => 45.4,
                'protein' => 3.1,
                'fat' => 2.2,
                'saturatedFat' => 0.4,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 4.4,
                'sugar' => 0.0,
                'dietaryFiber' => 3.3,
                'sodium' => 39.3,
                'calcium' => 105.4,
                'potassium' => 401.5,
                'ferrum' => 2.5,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:18:21',
                'updated_at' => '2019-12-01 15:18:21',
            ),
            89 => 
            array (
                'fdId' => 100,
                'rsId' => 2,
                'fdName' => '青江菜',
                'cId' => 1,
                'gram' => 102.0,
                'calorie' => 30.3,
                'protein' => 1.3,
                'fat' => 2.0,
                'saturatedFat' => 0.3,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 2.1,
                'sugar' => 0.3,
                'dietaryFiber' => 1.4,
                'sodium' => 47.0,
                'calcium' => 101.6,
                'potassium' => 224.6,
                'ferrum' => 1.0,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:19:04',
                'updated_at' => '2019-12-01 15:19:04',
            ),
            90 => 
            array (
                'fdId' => 101,
                'rsId' => 2,
                'fdName' => '空心菜',
                'cId' => 1,
                'gram' => 102.0,
                'calorie' => 38.8,
                'protein' => 2.0,
                'fat' => 2.1,
                'saturatedFat' => 0.3,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 3.5,
                'sugar' => 0.0,
                'dietaryFiber' => 2.5,
                'sodium' => 65.8,
                'calcium' => 70.4,
                'potassium' => 397.3,
                'ferrum' => 2.1,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:19:42',
                'updated_at' => '2019-12-01 15:19:42',
            ),
            91 => 
            array (
                'fdId' => 102,
                'rsId' => 2,
                'fdName' => '麵筋',
                'cId' => 4,
                'gram' => 52.0,
                'calorie' => 109.7,
                'protein' => 5.5,
                'fat' => 7.0,
                'saturatedFat' => 1.2,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 6.2,
                'sugar' => 0.0,
                'dietaryFiber' => 0.5,
                'sodium' => 389.0,
                'calcium' => 5.5,
                'potassium' => 46.5,
                'ferrum' => 0.9,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:20:16',
                'updated_at' => '2019-12-01 15:20:16',
            ),
            92 => 
            array (
                'fdId' => 103,
                'rsId' => 2,
                'fdName' => '大黃瓜炒黑輪',
                'cId' => 4,
                'gram' => 127.0,
                'calorie' => 74.8,
                'protein' => 3.8,
                'fat' => 3.2,
                'saturatedFat' => 0.5,
                'transFat' => 0.0,
                'cholesterol' => 5.0,
                'carbohydrate' => 8.0,
                'sugar' => 0.0,
                'dietaryFiber' => 0.7,
                'sodium' => 175.4,
                'calcium' => 12.9,
                'potassium' => 124.4,
                'ferrum' => 2.0,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:20:52',
                'updated_at' => '2019-12-01 15:20:52',
            ),
            93 => 
            array (
                'fdId' => 104,
                'rsId' => 2,
                'fdName' => '培根炒蛋',
                'cId' => 4,
                'gram' => 46.0,
                'calorie' => 106.8,
                'protein' => 5.7,
                'fat' => 9.1,
                'saturatedFat' => 3.8,
                'transFat' => 0.0,
                'cholesterol' => 129.1,
                'carbohydrate' => 0.6,
                'sugar' => 0.1,
                'dietaryFiber' => 0.0,
                'sodium' => 122.0,
                'calcium' => 13.6,
                'potassium' => 85.9,
                'ferrum' => 0.7,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:21:29',
                'updated_at' => '2019-12-01 15:21:29',
            ),
            94 => 
            array (
                'fdId' => 105,
                'rsId' => 2,
                'fdName' => '炒茄子',
                'cId' => 1,
                'gram' => 86.0,
                'calorie' => 36.9,
                'protein' => 0.9,
                'fat' => 2.0,
                'saturatedFat' => 0.3,
                'transFat' => 0.0,
                'cholesterol' => 0.0,
                'carbohydrate' => 4.1,
                'sugar' => 1.8,
                'dietaryFiber' => 1.8,
                'sodium' => 1.6,
                'calcium' => 11.6,
                'potassium' => 188.6,
                'ferrum' => 0.3,
                'photo' => 'http://120.110.112.96/qrfood/img/',
                'disable' => 0,
                'created_at' => '2019-12-01 15:22:05',
                'updated_at' => '2019-12-01 15:22:05',
            ),
            95 => 
            array (
                'fdId' => 106,
                'rsId' => 3,
                'fdName' => '豬肉炒泡麵',
                'cId' => 4,
                'gram' => 440.4,
                'calorie' => 395.09,
                'protein' => 26.19,
                'fat' => 25.22,
                'saturatedFat' => 9.47,
                'transFat' => 0.0,
                'cholesterol' => 344.77,
                'carbohydrate' => 15.87,
                'sugar' => 1.48,
                'dietaryFiber' => 6.96,
                'sodium' => 1424.17,
                'calcium' => 246.62,
                'potassium' => 1076.59,
                'ferrum' => 5.11,
                'photo' => 'http://120.110.112.96/qrfood/img/106.jpg',
                'disable' => 0,
                'created_at' => '2019-12-16 10:50:09',
                'updated_at' => '2019-12-16 10:50:09',
            ),
        ));
    }
}
